export class Urls {
}
Urls.absolutePath = new URL('https://www.forocoches.com/');
Urls.thread = new URL('https://www.forocoches.com/foro/showthread.php?t=');
Urls.whoPosted = new URL('https://www.forocoches.com/foro/misc.php?do=whoposted&t=');
Urls.post = new URL('https://www.forocoches.com/foro/showthread.php?p=');
Urls.deletePost = new URL('https://www.forocoches.com/foro/editpost.php');
Urls.user = new URL('https://www.forocoches.com/foro/member.php?u=');
Urls.quote = new URL('https://www.forocoches.com/foro/newreply.php?do=newreply&p=');
Urls.newPost = new URL('https://www.forocoches.com/foro/newreply.php?do=postreply&t=');
Urls.private = new URL('https://www.forocoches.com/foro/private.php');
Urls.ignoreList = new URL('https://www.forocoches.com/foro/profile.php?do=ignorelist');
Urls.contactList = new URL('https://www.forocoches.com/foro/profile.php?do=buddylist');
Urls.profile = new URL('https://www.forocoches.com/foro/profile.php');
Urls.usercp = new URL('https://www.forocoches.com/foro/usercp.php?');
Urls.userSearch = new URL('https://www.forocoches.com/foro/ajax.php?do=usersearch');
Urls.onlineUsers = new URL('https://www.forocoches.com/foro/online.php');
Urls.ajax = new URL('https://www.forocoches.com/foro/ajax.php');
Urls.forumDisplay = new URL('https://www.forocoches.com/foro/forumdisplay.php?f=');
Urls.showThread = new URL('https://www.forocoches.com/foro/showthread.php?t=');
